// opencl kernel on cells to apply attractive forces from nets, update position, locate cells to specific bins, and zero forces
//   a. For a given cell, I need to know all the nets connected to it
//   b. Then I need to look up all the other cells on those nets
//   c. Then I need to compute the bin x and y and use that to compute the bin index
//   d. Then I need to add the cell area to that bin's density
//   e. Use the bin's density to compute the repulsive forces


// Looking for smoothed density function - FFT
// move cells in direction of negative density gradient
// Decrease smoothing dependant on maximum gradient - Lipshitz coefficient
// They use an NxN grid and save previous repulsive forces


// Dynamic Hilbert R-Tree, sort by Hilbert number?
// Fast Gaussian Kernel Density Estimation via Dereche methods
// Linear binning
// 


// Current Plan for the Placement Algorithm
// Initial Delauny triangulation of points
// Global Iteration Step
//   Look for local violation of delauney graph
//     fix these violations in the delauney dataset
//   Walk Delauny triangulation to find nearest neighbors
//   Apply Electrostatic Gradiant to nearest neighbors within some range
//   Use Delauny Triangulation to compute natural interpolation (cubic? linear?) of derivative from nearest neighbors
//   Apply gradient to forces
//   Use nets to apply attractive force
//   Propagate forces to velocities and positions

// Other things that could be done:
//   There are 96 workgroups and each workgroup has a 512 wide SIMD compute
//   unit with shared memory. Break the problem apart by modules to identify
//   modules with less than 512 cells. This could be done fairly easily since
//   we can just look at the existing schematics generated by the dynamic
//   programming hierarchy flattening code. Then, run the solutions for those
//   modules to get initial positions without doing a global iteration step.
//   Then compute the initial position of those modules in the larger design,
//   place them, and do global iteration steps to compute the complete
//   solution.

// Number of edges for a delauny triangulation given N points is 3N - h - 3
// where h is the number of points on the convex hull. Therefore, maximum
// number of edges is 3N - 6 since smallest number of points on convex hull is
// 3, a single triangle. This is also the maximum number of edges for any
// convex hull triangulation. The problem with this approach is that ripping
// up a triangle will affect the ordering in the rest of the data structure.

// The maximum degree of a vertex is N-1 if N-1 points are cocircular and one
// point is in the center. The expected maximum degree of a vertex in a
// delauny triangulation is log(N)/log(log(N)). If we assume N is never larger
// 1T, then log(N) = 12 and 12/log(12) ~ 12. If we use N to compute the
// expected max, then if N is 300,000, then the expect max is ~ 8. Let's use N
// to compute the expected max and then double it.

// This means that the size of the neighbors array should be:
// 2*N*log(N)/log(log(N)) and the actual number of ports will be 2*(3*N-6)
// So in a 300,000 cell layout problem:
// neighbors.size() = 4,800,000
// Number of ports = 1,799,988
// Utilization is 37.5%
// In a 1,000,000,000 cell layout problem:
// neighbors.size() = 18,863,129,469 (17.57 GB)
// Number of ports = 5,999,999,988
// Utilization is 31.8%

// The other thing we can do is keep the cells sorted using a Hilbert curve so
// that any overflow has a high probability of only having local affects.
// However, that sorting process will become very expensive very quickly,
// expecially as vertices move.

// What if I use 4 rotated hilbert space filling curves and for each 2D point,
// I get a 4-valued position. The distance between two points is going to be
// the min of the distances between the four coordinates.
//   Rotated Hilbert curves still leave holes


inline uint hilbertFromCartesian(uint2 v) {
	uint state = 0, s = 0;
	for (uint i = 32; i > 0; i--) {
		uint row = 4*state | 2*((v.x >> (i-1)) & 1) | (v.y >> (i-1)) & 1;
		s = (s << 2) | (0x361E9CB4 >> 2*row) & 3;
		state = (0x8FE65831 >> 2*row) & 3;
	}
	return s;
}

inline uint2 cartesianFromHilbert(uint s) {
	uint2 vp = {0,0};
	uint state = 0;
	for (uint i = 2*32; i > 0; i -= 2) { // Do n times.
		uint row = 4*state | (s >> (i-2)) & 3; // Row in table.
		vp.x = (vp.x << 1) | (0x936C >> row) & 1;
		vp.y = (vp.y << 1) | (0x39C6 >> row) & 1;
		state = (0x3E6B94C1 >> 2*row) & 3; // New state.
	}
	return vp;
}


/*
// This is more of a sequential approach to sorting.
inline uint partition(
	uint* values,
	uint start,
	uint end,
	uint split) {
	uint left = start;
	uint right = end;

	while (left < right) {
		// Move left index forward while values[left] < split
		while (left < right && values[left] < split) {
			left++;
		}

		// Move right index backward while values[right - 1] >= split
		while (left < right && values[right - 1] >= split) {
			right--;
		}

		// Swap elements if left is still smaller than right
		if (left < right) {
			uint temp = values[left];
			values[left] = values[right - 1];
			values[right - 1] = temp;
			left++;
			right--;
		}
	}

	return left;
}*/


/*
Rather than do this, we should just randomly initialize the hilbert array and not bother setting the vertices

kernel void computeHilbert(
	global uint2* vertices,
	global uint* hilbert,
	const uint size,
	
) {
	uint i = get_global_id(0);
	if (i >= size) return;
	
	hilbert[i] = hilbertFromCartesian(vertices[i]);
}*/

/*
Rather than using random hilbert numbers and then computing the cartesian, we
should just initialize a perfectly balanced quad-tree with the existing
ordering and set the hilbert number equal to the location in the existing
array, then compute the cartesian position.

kernel void computeCartesian(
	global uint* hilbert,
	global uint2* vertices,
	const uint size,
	
) {
	uint i = get_global_id(0);
	if (i >= size) return;
	
	vertices[i] = cartesianFromHilbert(hilbert[i]);
}*/

/*kernel void buildQuadTree(
	global uint* hilbert,
	global uint* index,  // initialized as incremented value, moved with hilbert, used to index original cell
	const uint size,
	const uint pass,
	global uint* tree, // offsets into the hilbert array
	
	barrier

	

	// Cheng, Chung-Kuan, et al. "Replace: Advancing solution quality and
	// routability validation in global placement." IEEE Transactions on
	// Computer-Aided Design of Integrated Circuits and Systems 38.9 (2018):
	// 1717-1730.

	// Aizawa, Kunio, and Shojiro Tanaka. "A constant-time algorithm for finding
	// neighbors in quadtrees." IEEE Transactions on Pattern Analysis and Machine
	// Intelligence 31.7 (2008): 1178-1183.	

	// Holzmüller, David. "Efficient neighbor-finding on space-filling curves."
	// arXiv preprint arXiv:1710.06384 (2017).

	// Heer, Jeffrey. "Fast & accurate gaussian kernel density estimation." 2021
	// IEEE Visualization Conference (VIS). IEEE, 2021.

	// sort hilbert values and generate linear quadtree with level differences
	// stop quadtree such that leaves have at most L elements (Given that the
	// average degree of the delauny graph is 6 and the expected max is 12 for
	// large N, L should be between 7 and 13 to minimize time to find all
	// neighbors. This also means that the result doesn't have to be perfectly
	// sorted. For 1T elements, a balanced quad tree will have between 19 and 20
	// levels. For 300k elements, a balanced quad tree will have between 8 and 10
	// levels.
}*/

// TODO(edward.bingham) do I want to use morton codes instead of hilbert? Makes
// it easier to implement the constant-time neighbor search, and has similar
// properties


// Cells in the same module are going to be close to each other in the provided
// array!!!! This already creates the optimal distribution given the module
// hierarchy I should probably sort modules to minimize wire distance in the
// linear array as I am elaborating them. That would probably produce a better
// initial distribution in the hilbert space-filling curve. This could also be
// part of the canonicalization method for subcircuits with instances.
kernel void initPlacement(
	global uint2* position,
	global uint* index,  // initialized as incremented value, moved with hilbert, used to index original cell
	global uint* hilbert,
	global uint* areas,
	const uint num,
	const ulong total
) {
	uint i = get_global_id(0);
	if (i >= num) return;

	uint h = hilbert[i] * (UINT_MAX / total);
	uint2 p = cartesianFromHilbert(h);

	index[i] = i;
	position[i] = p;
}

kernel void stepPlacement(
	// Nets to Cells
	global uint* netsToCells,
	global uint* nets,
	// Cells to Nets
	global uint* cellsToNets,
	global uint* cells,
	// Delauny Triangulation
	global uint* neighbors, // At most 3*numCells-6 elements
	const int numNets,
	const int numCells,
	// Current positions of Cells
	global float2* positions,
	global float2* velocities,
	global float2* forces
) {
	uint i = get_global_id(0);
	if (i >= numCells) return;

  // Local variables for managing the workgroup's data
	uint groupSize = numCells / get_num_groups(0);
  uint groupStart = get_group_id(0) * groupSize;  // Start of this workgroup's segment of the array
	uint localSize = groupSize / get_local_size(0); 
  uint localStart = get_local_id(0)*localSize + groupStart;  // Local start index within the workgroup
  uint localEnd = localStart + localSize;  // Local end index within the workgroup

	// For *low frequency* repulsive forces:
	// The frequency is roughly equivalent to the level of the quadtree: level 0
	// is very low frequency, level 20 is very high frequency. The delauny
	// breadth first search is going to be very very expensive for the low
	// frequencies because every cell will have some effect on every other cell. So, 
	// instead we really just want to balance the quadtree at a given level so
	// that the total area of all cells in that quad is less than or equal to the
	// area covered by that quad with some coefficient (0.8 or something). At low
	// frequencies, we're dealing with a huge number of cells, and all large
	// distributions tend toward the normal distribution. So we want to find the
	// total cell area vs quad capacity as the amplitude of the normal
	// distribution and then determine the standard deviation of the distribution
	// within the cell. We also want to find the weighted average midpoint of the
	// distribution. Then we apply an electrostatic repulsion force from that
	// point to every cell roughly equal to that distribution. This will push
	// those cells apart in a way that is roughly equivalent to the low frequency
	// behaviors in RePlAce, but that is far far easier to compute.

	// For *high frequency* repulsive forces:
	// Use Quad-Tree to identify nearest neighbors that satisfy delauney triangulation
	// Use Quad-Tree to apply individual electrostatic repulsion forces to this point
	// Natural interpolation of nearest neighbors to compute gradient
}

